export const Catgory = [
  {
    name: "BURGER",
    img: "https://images4.alphacoders.com/248/248458.jpg",
  },
  {
    name: "CAKE",
    img: "https://th.bing.com/th/id/OIP.v1yZK5d8arevH6GefWcxlgHaE8?rs=1&pid=ImgDetMain",
  },
  {
    name: "PIZZA",
    img: "https://th.bing.com/th/id/OIP.BEH8rpIxoiUt_AQDRmSYTAHaFY?rs=1&pid=ImgDetMain",
  },
  {
    name: "BREAKFAST",
    img: "https://th.bing.com/th/id/OIP.d5iR9xE-7n8cm0VZ5WMcWQHaGL?rs=1&pid=ImgDetMain",
  },
  {
    name: "Salad",
    img: "https://th.bing.com/th/id/OIP.MCfSe1KisEXnFM5MZC3h3AHaFi?rs=1&pid=ImgDetMain",
  },
  {
    name: "Fruits",
    img: "https://th.bing.com/th/id/OIP.FxRpUZ1X5jvwyxjDJXeX4wHaGL?rs=1&pid=ImgDetMain",
  },
  {
    name: "Juice",
    img: "https://th.bing.com/th/id/OIP.aPcqRKSFq0_xFu02rZK_ogHaFj?rs=1&pid=ImgDetMain",
  },
];

const menu = [
  {
    id: 1,
    category: "BURGER",
    name: "Fasting Burger",
    Price: 295,
    img: "https://th.bing.com/th/id/OIP.9vOj25uyE-Aj7RUw1WM2xgHaE8?rs=1&pid=ImgDetMain",
  },
  {
    id: 2,
    category: "BURGER",
    name: "Special Burger",
    Price: 455,
    img: "https://th.bing.com/th/id/OIP.JnUimTk9WEG9Kz7RWBgmhwHaEu?rs=1&pid=ImgDetMain",
  },
  {
    id: 3,
    category: "BURGER",
    name: "Cheese Burger",
    Price: 400,
    img: "https://th.bing.com/th/id/R.dfcecfa23448e69ba48d49dd0111d2b8?rik=DFSQpZEMiFcQTw&riu=http%3a%2f%2fupload.wikimedia.org%2fwikipedia%2fcommons%2f4%2f4d%2fCheeseburger.jpg&ehk=jq7nmMsmFI2ZD1lF2sjvQFyFs%2faksW%2fAQa5pJ7GaIBE%3d&risl=&pid=ImgRaw&r=0",
  },
  {
    id: 4,
    category: "BURGER",
    name: "Beef Burger",
    Price: 400,
    img: "https://th.bing.com/th/id/OIP.NSfyTqmOCuBUqqFsrTWQFQHaHa?rs=1&pid=ImgDetMain",
  },
  {
    id: 5,
    category: "BURGER",
    name: "Chicken Burger",
    Price: 455,
    img: "https://www.chicken.ca/wp-content/uploads/2020/09/Moist-Chicken-Burgers.jpg",
  },
  {
    id: 6,
    category: "BURGER",
    name: "Egg Sandwich",
    Price: 250,
    img: "https://th.bing.com/th/id/R.a7a9cce07a98c78a71055f0c4226bbbb?rik=OTKxk8r2bGtdWA&pid=ImgRaw&r=0",
  },
  {
    id: 7,
    category: "BURGER",
    name: "Tuna Sandwich",
    Price: 295,
    img: "https://th.bing.com/th/id/R.7cb20b2fdce31b85365d01009965b96f?rik=eV62%2blNa%2fTA0Sw&pid=ImgRaw&r=0",
  },
  {
    id: 8,
    category: "BURGER",
    name: "Egg Scramble",
    Price: 210,
    img: "https://tastefullygrace.com/wp-content/uploads/2022/12/How-to-Make-Scrambled-Eggs-2-scaled.jpg",
  },
  {
    id: 9,
    category: "BURGER",
    name: "Vegetable Sandwich",
    Price: 205,
    img: "https://th.bing.com/th/id/OIP.4kFQpwk0gIitJQf2O6go1AHaFj?rs=1&pid=ImgDetMain",
  },
  {
    id: 10,
    category: "CAKE",
    name: "Black / White F",
    Price: 75,
    img: "https://th.bing.com/th/id/OIP.knCpsFYBJnkV_zD7Y9EVigHaHa?rs=1&pid=ImgDetMain",
  },
  {
    id: 11,
    category: "CAKE",
    name: "Bombolino / Koker",
    Price: 50,
    img: "https://th.bing.com/th/id/OIP.CxRGIYteNo40g4A2gAwzSwHaFj?rs=1&pid=ImgDetMain",
  },
  {
    id: 12,
    category: "CAKE",
    name: "Teramiso",
    Price: 75,
    img: "https://th.bing.com/th/id/OIP.8-hIBxuk2aR5lmY7CHN38wHaE7?rs=1&pid=ImgDetMain",
  },
  {
    id: 13,
    category: "CAKE",
    name: "Tekorach Cake",
    Price: 50,
    img: "https://i.ytimg.com/vi/wBbupkIKtjI/maxresdefault.jpg",
  },
  {
    id: 14,
    category: "CAKE",
    name: "Torta Cake",
    Price: 700,
    img: "https://th.bing.com/th/id/OIP.dDkG-9taFOwuBteC_MQArgHaHa?rs=1&pid=ImgDetMain",
  },
  {
    id: 15,
    category: "CAKE",
    name: "Foil",
    Price: 35,
    img: "https://i.ytimg.com/vi/9xfvfttx5GU/maxresdefault.jpg",
  },
  {
    id: 16,
    category: "CAKE",
    name: "Cake Take Away Paper",
    Price: 25,
    img: "https://th.bing.com/th/id/OIP.lE5jpOXOjuieIPhdVqK0VAHaHa?rs=1&pid=ImgDetMain",
  },
  {
    id: 17,
    category: "CAKE",
    name: "Take Away Juice Cup",
    Price: 25,
    img: "https://th.bing.com/th/id/OIP.OL3CN3p1_AQcNqq-MJomKwHaGo?rs=1&pid=ImgDetMain",
  },
  {
    id: 18,
    category: "CAKE",
    name: "Torta Cake Box",
    Price: 50,
    img: "https://th.bing.com/th/id/R.04224899355516df06062c2c61678b75?rik=fE1lIrxXzV%2bq%2fg&riu=http%3a%2f%2f1.bp.blogspot.com%2f-kN8m4hlzlYY%2fTWZoDnz5V5I%2fAAAAAAAAARU%2f-_hcgFBwxr4%2fs1600%2fblack%2bmagic%2bcupcakes.jpg&ehk=9mxNNJIPV2r%2b7YGSuqnsFxha%2fRDXckEbFFRnStH9kw8%3d&risl=&pid=ImgRaw&r=0",
  },
  {
    id: 19,
    category: "CAKE",
    name: "Pizza Take Away",
    Price: 25,
    img: "https://www.littleoverlodge.co.uk/wp-content/uploads/2018/08/pizza-restaurants-derby-takeaway-option.jpg",
  },
  {
    id: 20,
    category: "PIZZA",
    name: "Special Pizz",
    Price: 460,
    img: "https://th.bing.com/th/id/OIP.ft2vr4OqwlodS_sD9eI8GAHaFE?rs=1&pid=ImgDetMain",
  },
  {
    id: 21,
    category: "PIZZA",
    name: "Tuna Pizza",
    Price: 475,
    img: "https://images.eatsmarter.com/sites/default/files/styles/facebook/public/tuna-pizza-519466.jpg",
  },
  {
    id: 22,
    category: "PIZZA",
    name: "Margarita Pizza",
    Price: 400,
    img: "https://th.bing.com/th/id/R.f7cd06aac470a198e0f78a93b9574167?rik=wwuBELWLD%2ftDJg&pid=ImgRaw&r=0",
  },
  {
    id: 23,
    category: "PIZZA",
    name: "Vegetable Pizza",
    Price: 370,
    img: "https://th.bing.com/th/id/R.6f5d38e82769f86451421d32de95242b?rik=BtMNUzODcZ0nmA&pid=ImgRaw&r=0",
  },
  {
    id: 24,
    category: "PIZZA",
    name: "Chicken Pizza",
    Price: 600,
    img: "https://th.bing.com/th/id/OIP.wyGb_snDrZ-ZSVFXtgYMfAAAAA?rs=1&pid=ImgDetMain",
  },
  {
    id: 25,
    category: "PIZZA",
    name: "Club Sandwich",
    Price: 500,
    img: "https://th.bing.com/th/id/R.744c84bea7c61fad933497e23ab2f2da?rik=XUcQvbvPOM7yLQ&riu=http%3a%2f%2fcdn.taste.com.au%2fimages%2frecipes%2fsfi%2f2005%2f07%2f1018.jpg&ehk=45WmqnZucECJnQ4wEgA1lZ43QP1MLSldWj%2fqD%2bs%2fGY0%3d&risl=&pid=ImgRaw&r=0",
  },
  {
    id: 26,
    category: "PIZZA",
    name: "Club Sandwich Half",
    Price: 365,
    img: "https://purepng.com/public/uploads/large/purepng.com-sandwichfood-slice-salad-tasty-bread-vegetable-health-delicious-breakfast-sandwich-9415246186167yco8.png",
  },
  {
    id: 27,
    category: "PIZZA",
    name: "Mercy Cheeps",
    Price: 155,
    img: "https://th.bing.com/th/id/R.6e094453ed99ed8a810520b56fc92cca?rik=dM1zmyr5a1mttQ&riu=http%3a%2f%2fimg.taste.com.au%2fMudZOM3z%2ftaste%2f2016%2f11%2ffrench-fries-87711-1.jpeg&ehk=t1TZByWsonGmHwgvlRbxjsRsO%2fwV4HWSYbFXzwOdVpk%3d&risl=&pid=ImgRaw&r=0",
  },
  {
    id: 28,
    category: "BREAKFAST",
    name: "Pancake",
    Price: 250,
    img: "https://www.bakingstherapy.com/wp-content/uploads/2020/07/DSC_8098-1-1.jpg",
  },
  {
    id: 29,
    category: "BREAKFAST",
    name: "Special Omelat",
    Price: 275,
    img: "https://th.bing.com/th/id/OIP.t1ZNDrYtB3qFb4dW_4IAnwHaE8?rs=1&pid=ImgDetMain",
  },
  {
    id: 30,
    category: "BREAKFAST",
    name: "Cheese Omelat",
    Price: 250,
    img: "https://th.bing.com/th/id/OIP.TSubyrrh0xZsTMcgTbb-6AHaE8?rs=1&pid=ImgDetMain",
  },
  {
    id: 31,
    category: "BREAKFAST",
    name: "Normal Omelat",
    Price: 200,
    img: "https://th.bing.com/th/id/OIP.lP8SyISigcitxXSe0CtakwHaHa?rs=1&pid=ImgDetMain",
  },
  {
    id: 32,
    category: "BREAKFAST",
    name: "Special Omelat",
    Price: 250,
    img: "https://bakeitwithlove.com/wp-content/uploads/2021/11/cheese-omelet-sq.jpg",
  },
  {
    id: 33,
    category: "BREAKFAST",
    name: "Fasting tiebs",
    Price: 280,
    img: "https://th.bing.com/th/id/R.5592a2f63036324d183ae0f26c859c16?rik=ZmpPl5MxiW3pPQ&pid=ImgRaw&r=0",
  },
  {
    id: 34,
    category: "Salad",
    name: "Mercy Combo Salad",
    Price: 455,
    img: "https://th.bing.com/th/id/OIP.uqsF-n1miMR6SUU_qgB8nwHaHa?rs=1&pid=ImgDetMain",
  },
  {
    id: 35,
    category: "Salad",
    name: "Mercy Combo Salad Half",
    Price: 365,
    img: "https://anaayafoods.com/wp-content/uploads/2016/06/combination-salad-recipe-768x512.jpg",
  },
  {
    id: 36,
    category: "Salad",
    name: "Mercy Special Fruit Platter",
    Price: 455,
    img: "https://th.bing.com/th/id/R.385a59da4a56a3ed3b9150ce52ada4ff?rik=%2bhgqb1cQjedQFw&pid=ImgRaw&r=0",
  },
  {
    id: 37,
    category: "Salad",
    name: "Mercy Special Salad",
    Price: 405,
    img: "https://th.bing.com/th/id/OIP.Ycq7mL_Ndcmt8hva0QML4QHaLH?rs=1&pid=ImgDetMain",
  },
  {
    id: 38,
    category: "Salad",
    name: "Mercy Special Tuna Salad",
    Price: 500,
    img: "https://th.bing.com/th/id/R.6b4c16fe9b27173900e1530b3f6de03d?rik=WidlZOjE0GkxOg&pid=ImgRaw&r=0",
  },
  {
    id: 39,
    category: "Salad",
    name: "Mercy Special Tuna Salad Half",
    Price: 405,
    img: "https://www.deliciousmeetshealthy.com/wp-content/uploads/2020/06/Mediterranean-Tuna-Salad-7.jpg",
  },
  {
    id: 40,
    category: "Salad",
    name: "Fish Salad",
    Price: 455,
    img: "https://th.bing.com/th/id/OIP.gPODnSW2ifXHj6Sd4S3JQAHaE5?rs=1&pid=ImgDetMain",
  },
  {
    id: 41,
    category: "Salad",
    name: "Fish Salad Half",
    Price: 405,
    img: "https://th.bing.com/th/id/OIP.tMsSJ-Rte7COoFEQ0R-URgHaHa?rs=1&pid=ImgDetMain",
  },
  {
    id: 42,
    category: "Salad",
    name: "Fruit Plater Salad",
    Price: 405,
    img: "https://th.bing.com/th/id/R.7c67b9cd997828676b45e34f41cc9f5b?rik=xaVxNjHgpZSZmw&pid=ImgRaw&r=0",
  },
  {
    id: 43,
    category: "Salad",
    name: "Mixed Salad",
    Price: 355,
    img: "https://th.bing.com/th/id/R.c0e6b4b9d7ae85e5dbf4ccb096012b8c?rik=P4P6JXXec3mFMg&riu=http%3a%2f%2fnaturalfitfoodie.com%2fwp-content%2fuploads%2f2016%2f07%2fMixed-Green-Summer-Salad-6.jpg&ehk=XOrDuyTzWrIvznC%2b1KzBkZYkQ8zY9ludqMm%2f8YrwRJk%3d&risl=&pid=ImgRaw&r=0",
  },
  {
    id: 44,
    category: "Salad",
    name: "Fruit Punche",
    Price: 355,
    img: "https://th.bing.com/th/id/OIP.ugXbfZZealw6AUyQuTLQDgHaJO?rs=1&pid=ImgDetMain",
  },
  {
    id: 45,
    category: "Fruits",
    name: "Lemon 1KG",
    Price: 160,
    img: "https://th.bing.com/th/id/R.b1dbe95d486bfd6b66ce0a4162f5d88a?rik=CLHGTwLNapIudQ&pid=ImgRaw&r=0",
  },
  {
    id: 46,
    category: "Fruits",
    name: "Papaya 1KG ",
    Price: 80,
    img: "https://th.bing.com/th/id/OIP._E7vO0DtjDOF8OOEg0A7ygHaHa?rs=1&pid=ImgDetMain",
  },
  {
    id: 47,
    category: "Fruits",
    name: "Banana 1KG",
    Price: 60,
    img: "https://th.bing.com/th/id/OIP.RKzD7j8N8vfQognyk7IEFgHaFF?w=1024&h=703&rs=1&pid=ImgDetMain",
  },
  {
    id: 48,
    category: "Fruits",
    name: "Orange 1KG",
    Price: 250,
    img: "https://th.bing.com/th/id/R.946e60c37e740543ca2322d04626f440?rik=4kg1LMGJBy4K4g&pid=ImgRaw&r=0",
  },
  {
    id: 49,
    category: "Fruits",
    name: "Mango 1KG",
    Price: 110,
    img: "https://img3.exportersindia.com/product_images/bc-full/dir_136/4073908/fresh-mangoes-1475140963-2414258.jpeg",
  },
  {
    id: 50,
    category: "Fruits",
    name: "Water Melon Big 1KG",
    Price: 80,
    img: "https://th.bing.com/th/id/OIP.4sJ0LqbOcntI7ncDYcd18gHaEO?rs=1&pid=ImgDetMain",
  },
  {
    id: 51,
    category: "Fruits",
    name: "Apple",
    Price: 330,
    img: "https://th.bing.com/th/id/OIP.u5DTTr4yqJwv1JSf94GEzAHaFR?rs=1&pid=ImgDetMain",
  },
  {
    id: 52,
    category: "Fruits",
    name: "PinApple 1Pice",
    Price: 100,
    img: "https://th.bing.com/th/id/OIP.RdQ_VZPT8eAS7Shcys20UAHaHa?rs=1&pid=ImgDetMain",
  },
  {
    id: 53,
    category: "Fruits",
    name: "Gishta 1KG",
    Price: 90,
    img: "https://www.plantsville.in/wp-content/uploads/2022/06/Soursop-.jpg",
  },
  {
    id: 54,
    category: "Fruits",
    name: "Avocado 1KG",
    Price: 110,
    img: "https://th.bing.com/th/id/R.c72d7edfe419495937dc5c02bbcd85e7?rik=hRc18WgImzh3iw&riu=http%3a%2f%2fmassageinflorida.com%2fblog%2fwp-content%2fuploads%2f2012%2f04%2fAvocado-5918425_l1.jpg&ehk=kQRbjSajWN54cFW8D1%2fm6wLdOE3Fz8mu5K7aGxN12Q0%3d&risl=&pid=ImgRaw&r=0",
  },
  {
    id: 55,
    category: "Juice",
    name: "Mercy Special Juice",
    Price: 82,
    img: "https://th.bing.com/th/id/R.fd74d604740fdcdf47f41f3f47d12a6c?rik=xDdAJbMX%2bOqirQ&pid=ImgRaw&r=0",
  },
  {
    id: 56,
    category: "Juice",
    name: "Mercy Smoothie juice",
    Price: 215,
    img: "https://th.bing.com/th/id/R.4a7aa53c67ccf1f571536040b35064a2?rik=ZmzGeLLwcoFEnw&pid=ImgRaw&r=0",
  },
  {
    id: 57,
    category: "Juice",
    name: "Mercy Chuckhole Shake ",
    Price: 222,
    img: "https://th.bing.com/th/id/R.c7f2a7962cd211e244e781b9292c3b0a?rik=c1G23WPuiDmx3w&pid=ImgRaw&r=0",
  },
  {
    id: 58,
    category: "Juice",
    name: "Mercy Milk Shake",
    Price: 172,
    img: "https://th.bing.com/th/id/OIP.BVibYyjlZtVp5udAbXXirgHaHa?rs=1&pid=ImgDetMain",
  },
  {
    id: 59,
    category: "Juice",
    name: "Juice With Cream",
    Price: 220,
    img: "https://th.bing.com/th/id/R.eb2210c5b7f06aa3395cf0181939ef55?rik=2LKkk79JvKcyhA&pid=ImgRaw&r=0",
  },
  {
    id: 60,
    category: "Juice",
    name: "Sprice Juice",
    Price: 452,
    img: "https://3.bp.blogspot.com/_EIXk-7Ftokg/S76ybcQ1daI/AAAAAAAAFEU/taCVun0tYls/s1600/100_1029.JPG",
  },
  {
    id: 61,
    category: "Juice",
    name: "Apple Juice ",
    Price: 250,
    img: "https://www.archanaskitchen.com/images/archanaskitchen/World_Beverages/Mulled_Apple_Juice_Recipe-1.jpg",
  },
  {
    id: 62,
    category: "Juice",
    name: "Mango Juice ",
    Price: 135,
    img: "https://images.absolutdrinks.com/ingredient-images/Raw/Absolut/458df6af-9594-43f3-bc8d-fb25361bd2e4.jpg?imwidth=500",
  },
  {
    id: 63,
    category: "Juice",
    name: "Avocado Juice ",
    Price: 125,
    img: "https://i.pinimg.com/originals/28/27/1e/28271e7bbda9c6337ecc56622dc3ca28.jpg",
  },
  {
    id: 64,
    category: "Juice",
    name: "Papaya Juice",
    Price: 122,
    img: "https://th.bing.com/th/id/OIP.ephN2i_ieMU6jsA6ciodOwHaFS?rs=1&pid=ImgDetMain",
  },
  {
    id: 65,
    category: "Juice",
    name: "Water Melon Juice",
    Price: 125,
    img: "https://th.bing.com/th/id/OIP.N4fBPypLQdZYkRP-df0nkAHaLH?rs=1&pid=ImgDetMain",
  },
  {
    id: 66,
    category: "Juice",
    name: "Strawberry Juice",
    Price: 205,
    img: "https://th.bing.com/th/id/R.fff75a2a4b31f4f9d68ed84904f5c328?rik=bJSjWYh9tTrUkg&riu=http%3a%2f%2fcdn3.foodviva.com%2fstatic-content%2ffood-images%2fjuice-recipes%2fstrawberry-juice-recipe%2fstrawberry-juice-recipe.jpg&ehk=5NOPVrOcUiVgE3EKYsdEIBtAuXAZolsHgL5YBNhlNk8%3d&risl=&pid=ImgRaw&r=0",
  },
  {
    id: 67,
    category: "Juice",
    name: "Banana Juice",
    Price: 100,
    img: "https://th.bing.com/th/id/OIP.cVR8DVsG7GG92anTqqEqKAHaD4?rs=1&pid=ImgDetMain",
  },
  {
    id: 68,
    category: "Juice",
    name: "Gishta Juice",
    Price: 125,
    img: "https://th.bing.com/th/id/OIP.mpMc0L52n793a3xjl6gNtAHaLH?w=720&h=1080&rs=1&pid=ImgDetMain",
  },
  {
    id: 69,
    category: "Juice",
    name: "Orange Juice",
    Price: 250,
    img: "https://th.bing.com/th/id/OIP.jqxR_QrdtXQR6kfXBUHrBAHaFD?rs=1&pid=ImgDetMain",
  },
  {
    id: 70,
    category: "Juice",
    name: "Pineapple Juice",
    Price: 155,
    img: "https://th.bing.com/th/id/R.86515b09dd77cce5661c0f3550f55b48?rik=MnEIqQklWOKgkg&pid=ImgRaw&r=0",
  },
  {
    id: 71,
    category: "Juice",
    name: "Strawberry Shake",
    Price: 215,
    img: "https://th.bing.com/th/id/OIP.XzeyKVSg88qntLhnxZxvvwHaNK?rs=1&pid=ImgDetMain",
  },
  {
    id: 72,
    category: "Juice",
    name: "HOPY Juice ",
    Price: 125,
    img: "https://th.bing.com/th/id/OIP.k8ZYlpuvW1P7VmsOqkT4owHaLH?rs=1&pid=ImgDetMain",
  },
  {
    id: 73,
    category: "Juice",
    name: "Strawberry Pack",
    Price: 170,
    img: "https://thumbs.dreamstime.com/b/strawberries-pack-closeup-view-sale-46031367.jpg",
  },
];
export default menu;
